ls:
  .dir: kebabcase | screamingsnakecase
  .md: kebabcase | screamingsnakecase
  .js: kebabcase
  .jsx: kebabcase
  .mjs: kebabcase
  .cjs: kebabcase
  .ts: kebabcase
  .tsx: kebabcase
  .*.js: kebabcase
  .*.jsx: kebabcase
  .*.mjs: kebabcase
  .*.cjs: kebabcase
  .*.ts: kebabcase
  .*.tsx: kebabcase

ignore:
  - .changeset
  - .git
  - .github
  - .turbo
  - .vscode
  - .windsurf
  - '**/.next'
  - '**/.ladle'
  - '**/.storybook'
  - '**/.turbo'
  - '**/__fixtures__'
  - '**/__snapshots__'
  - '**/build'
  - '**/coverage'
  - '**/dist'
  - '**/documentation'
  - '**/node_modules'
  - 'apps/docs/.docusaurus'
  - 'apps/docs/content/api'
