/*
 * Copyright 2025 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const TYPEDOC_OUTPUT_DIR = 'api';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      id: `${TYPEDOC_OUTPUT_DIR}/README`,
      label: 'DevTK',
      type: 'doc',
    },
    {
      collapsed: false,
      label: 'Packages',
      items: [
        { dirName: `${TYPEDOC_OUTPUT_DIR}/@accelint`, type: 'autogenerated' },
      ],
      type: 'category',
    },
  ],
  // demoSidebar: [
  //   {
  //     items: [{ type: 'autogenerated', dirName: 'packages' }],
  //     label: 'group 1',
  //     type: 'category',
  //   },
  //   {
  //     items: [{ type: 'autogenerated', dirName: 'config' }],
  //     label: 'group 2',
  //     type: 'category',
  //   },
  // ],
};

export default sidebars;
