/*
 * Copyright 2025 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * THIS IS A GENERATED FILE. DO NOT ALTER DIRECTLY.
 * Generated by smeegl.
 */

export const AIR_ASSUMED_FRIEND = '1949571830';
export const AIR_BASE_FRIEND = '551414551';
export const AIR_BASE_HOSTILE = '3780933729';
export const AIR_BASE_UNKNOWN = '3968770410';
export const AIR_FRIEND = '978699787';
export const AIR_GROUP_FRIEND = '2286505001';
export const AIR_GROUP_HOSTILE = '546697581';
export const AIR_GROUP_UNKNOWN = '759638118';
export const AIR_HOSTILE = '4115115011';
export const AIR_NEUTRAL = '2912761496';
export const AIR_PENDING = '3765206818';
export const AIR_SUSPECT = '2803930820';
export const AIR_UNKNOWN = '4170544392';
export const BASE_FRIEND = '543001814';
export const BASE_HOSTILE = '222235168';
export const BASE_UNKNOWN = '15586091';
export const CARRIER_FRIEND = '704947060';
export const CARRIER_HOSTILE = '904761803';
export const CARRIER_UNKNOWN = '943671488';
export const COMMUNICATIONS = '2789949762';
export const HELICOPTER_FRIEND = '2500966045';
export const HELICOPTER_HOSTILE = '3968130562';
export const HELICOPTER_UNKNOWN = '3780511497';
export const LAND_ASSUMED_FRIEND = '2759182567';
export const LAND_FRIEND = '2778734184';
export const LAND_HOSTILE = '560163129';
export const LAND_NEUTRAL = '2042229666';
export const LAND_PENDING = '877181464';
export const LAND_SUSPECT = '1929663486';
export const LAND_UNKNOWN = '749842482';
export const MINE_FIELD = '2944877008';
export const MISSILE_FRIEND = '1035975297';
export const MISSILE_HOSTILE = '4163710017';
export const MISSILE_UNKNOWN = '4127192394';
export const POL = '1754074137';
export const PORT = '1121828031';
export const RUNWAY = '3425672619';
export const SAM = '1578065476';
export const STRUCTURE = '3244155986';
export const SUB_GROUP_FRIEND = '2137646837';
export const SUB_GROUP_HOSTILE = '2936491832';
export const SUB_GROUP_UNKNOWN = '2731906611';
export const SUB_SURFACE_ASSUMED_FRIEND = '1620272216';
export const SUB_SURFACE_FRIEND = '154913688';
export const SUB_SURFACE_HOSTILE = '2624717040';
export const SUB_SURFACE_NEUTRAL = '3299383915';
export const SUB_SURFACE_PENDING = '2304365521';
export const SUB_SURFACE_SUSPECT = '3457497655';
export const SUB_SURFACE_UNKNOWN = '2443237883';
export const SURFACE_ASSUMED_FRIEND = '970098970';
export const SURFACE_FRIEND = '1172078186';
export const SURFACE_GROUP_FRIEND = '2762606047';
export const SURFACE_GROUP_HOSTILE = '1952924941';
export const SURFACE_GROUP_UNKNOWN = '2041945094';
export const SURFACE_HOSTILE = '3482154101';
export const SURFACE_NEUTRAL = '2539122414';
export const SURFACE_PENDING = '3668354900';
export const SURFACE_SUSPECT = '2649378482';
export const SURFACE_UNKNOWN = '3261050238';
export const TARGET = '534167708';
export const TORPEDO_FRIEND = '1778325685';
export const TORPEDO_HOSTILE = '3654129750';
export const TORPEDO_UNKNOWN = '3558818141';
