---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "@accelint/map-toolkit"
  title: Accelint Map Toolkit
  description: >-
    A collection of components and utilities to simplify visualizing and working
    with geospatial data.


    Dependencies:

    @accelint/biome-config@1.0.0, @accelint/constellation-tracker@0.0.0,
    @accelint/design-toolkit@5.0.0, @accelint/typescript-config@0.1.2,
    @accelint/vitest-config@0.1.3
  annotations:
    backstage.io/edit-url: https://github.com/gohypergiant/standard-toolkit/blob/main/packages/map-toolkit/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
    package/version: 0.0.2
    github.com/project-slug: gohypergiant/standard-toolkit
  links:
    - url: https://github.com/gohypergiant/standard-toolkit/tree/main/packages/map-toolkit
      title: Documentation
      icon: docs
      type: documentation
  tags:
    - deckgl
    - geospatial
    - map-tk
    - maplibre
spec:
  type: library
  lifecycle: production
  owner: group:default/pathfinder
  dependsOn:
    - component:@accelint/biome-config
    - component:@accelint/constellation-tracker
    - component:@accelint/design-toolkit
    - component:@accelint/typescript-config
    - component:@accelint/vitest-config
