/*
 * Copyright 2025 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import * as Icon from '@accelint/icons';

export default {
  actions: {
    description:
      'These icons mainly represent an act a user can take in the user interface.',
    icons: [
      { name: 'add-fill', icon: <Icon.AddFill /> },
      { name: 'add-to-list', icon: <Icon.AddToList /> },
      { name: 'add', icon: <Icon.Add /> },
      { name: 'arrange-table', icon: <Icon.ArrangeTable /> },
      { name: 'attach-file', icon: <Icon.AttachFile /> },
      { name: 'cancel', icon: <Icon.Cancel /> },
      { name: 'cancel-fill', icon: <Icon.CancelFill /> },
      { name: 'center-on', icon: <Icon.CenterOn /> },
      { name: 'check', icon: <Icon.Check /> },
      { name: 'collapse-window', icon: <Icon.CollapseWindow /> },
      { name: 'collapse-all', icon: <Icon.CollapseAll /> },
      { name: 'condense', icon: <Icon.Condense /> },
      { name: 'copy-to-clipboard', icon: <Icon.CopyToClipboard /> },
      { name: 'create-coa', icon: <Icon.CreateCoa /> },
      { name: 'delete', icon: <Icon.Delete /> },
      { name: 'drag-horz', icon: <Icon.DragHorz /> },
      { name: 'drag-vert', icon: <Icon.DragVert /> },
      { name: 'duplicate', icon: <Icon.Duplicate /> },
      { name: 'edit', icon: <Icon.Edit /> },
      { name: 'expand-all', icon: <Icon.ExpandAll /> },
      { name: 'expand-left', icon: <Icon.ExpandLeft /> },
      { name: 'expand-left-panel', icon: <Icon.ExpandLeftPanel /> },
      { name: 'expand-right', icon: <Icon.ExpandRight /> },
      { name: 'expand-window', icon: <Icon.ExpandWindow /> },
      { name: 'expand', icon: <Icon.Expand /> },
      { name: 'explore-data', icon: <Icon.ExploreData /> },
      { name: 'filter', icon: <Icon.Filter /> },
      { name: 'flag', icon: <Icon.Flag /> },
      { name: 'focus', icon: <Icon.Focus /> },
      { name: 'global-share', icon: <Icon.GlobalShare /> },
      { name: 'group', icon: <Icon.Group /> },
      { name: 'hide', icon: <Icon.Hide /> },
      { name: 'import', icon: <Icon.Import /> },
      { name: 'insert-chart', icon: <Icon.InsertChart /> },
      { name: 'jump-to', icon: <Icon.JumpTo /> },
      { name: 'lasso', icon: <Icon.Lasso /> },
      { name: 'link', icon: <Icon.Link /> },
      { name: 'lock-fill', icon: <Icon.LockFill /> },
      { name: 'lock-outline', icon: <Icon.LockOutline /> },
      { name: 'login', icon: <Icon.Login /> },
      { name: 'logout', icon: <Icon.Logout /> },
      { name: 'loop', icon: <Icon.Loop /> },
      { name: 'move', icon: <Icon.Move /> },
      { name: 'mute', icon: <Icon.Mute /> },
      { name: 'open-container', icon: <Icon.OpenContainer /> },
      { name: 'paste-from-clipboard', icon: <Icon.PasteFromClipboard /> },
      { name: 'pause', icon: <Icon.Pause /> },
      { name: 'pin', icon: <Icon.Pin /> },
      { name: 'play', icon: <Icon.Play /> },
      { name: 'playback', icon: <Icon.Playback /> },
      { name: 'polygon-lasso', icon: <Icon.PolygonLasso /> },
      { name: 'pop-back-in', icon: <Icon.PopBackIn /> },
      { name: 'pop-out', icon: <Icon.PopOut /> },
      { name: 'record', icon: <Icon.Record /> },
      { name: 'rectangle-select', icon: <Icon.RectangleSelect /> },
      { name: 'remove-fill', icon: <Icon.RemoveFill /> },
      { name: 'remove-from-list', icon: <Icon.RemoveFromList /> },
      { name: 'remove', icon: <Icon.Remove /> },
      { name: 'reverse', icon: <Icon.Reverse /> },
      { name: 'screenshot', icon: <Icon.Screenshot /> },
      { name: 'search', icon: <Icon.Search /> },
      { name: 'share', icon: <Icon.Share /> },
      { name: 'show', icon: <Icon.Show /> },
      { name: 'stack-cards', icon: <Icon.StackCards /> },
      { name: 'stack', icon: <Icon.Stack /> },
      { name: 'tether', icon: <Icon.Tether /> },
      { name: 'track-changes', icon: <Icon.TrackChanges /> },
      { name: 'undo', icon: <Icon.Undo /> },
      { name: 'zoom-in', icon: <Icon.ZoomIn /> },
      { name: 'zoom-out', icon: <Icon.ZoomOut /> },
      { name: 'zoom-to', icon: <Icon.ZoomTo /> },
    ],
  },
  symbols: {
    description: 'These icons mainly represent an object or concept.',
    icons: [
      { name: 'airspaces', icon: <Icon.Airspaces /> },
      { name: 'appearance', icon: <Icon.Appearance /> },
      { name: 'arrow', icon: <Icon.Arrow /> },
      { name: 'ascending', icon: <Icon.Ascending /> },
      { name: 'assignment', icon: <Icon.Assignment /> },
      { name: 'attributes', icon: <Icon.Attributes /> },
      { name: 'bolt-not-visible', icon: <Icon.BoltNotVisible /> },
      { name: 'bolt', icon: <Icon.Bolt /> },
      { name: 'brightness', icon: <Icon.Brightness /> },
      { name: 'bug-report', icon: <Icon.BugReport /> },
      { name: 'calendar', icon: <Icon.Calendar /> },
      { name: 'chart-stacked-bar', icon: <Icon.ChartStackedBar /> },
      { name: 'circle-tool', icon: <Icon.CircleTool /> },
      { name: 'color-picker', icon: <Icon.ColorPicker /> },
      { name: 'common-operating-pic', icon: <Icon.CommonOperatingPic /> },
      { name: 'contrast', icon: <Icon.Contrast /> },
      { name: 'cop-settings', icon: <Icon.CopSettings /> },
      { name: 'coverage', icon: <Icon.Coverage /> },
      { name: 'dashboard', icon: <Icon.Dashboard /> },
      { name: 'data', icon: <Icon.Data /> },
      { name: 'descending', icon: <Icon.Descending /> },
      {
        name: 'electromagnetic-spectrum',
        icon: <Icon.ElectromagneticSpectrum />,
      },
      { name: 'feed', icon: <Icon.Feed /> },
      { name: 'flight-plan', icon: <Icon.FlightPlan /> },
      { name: 'gantt', icon: <Icon.Gantt /> },
      { name: 'grid', icon: <Icon.Grid /> },
      { name: 'hamburger', icon: <Icon.Hamburger /> },
      { name: 'handover', icon: <Icon.Handover /> },
      { name: 'handshake', icon: <Icon.Handshake /> },
      { name: 'help', icon: <Icon.Help /> },
      { name: 'intercept-point', icon: <Icon.InterceptPoint /> },
      { name: 'kebab', icon: <Icon.Kebab /> },
      { name: 'layer-group', icon: <Icon.LayerGroup /> },
      { name: 'layers', icon: <Icon.Layers /> },
      { name: 'line-tool', icon: <Icon.LineTool /> },
      { name: 'location-fill', icon: <Icon.LocationFill /> },
      { name: 'location-stroke', icon: <Icon.LocationStroke /> },
      { name: 'message', icon: <Icon.Message /> },
      { name: 'mode', icon: <Icon.Mode /> },
      { name: 'newspaper', icon: <Icon.Newspaper /> },
      { name: 'non-editable', icon: <Icon.NonEditable /> },
      { name: 'none', icon: <Icon.None /> },
      { name: 'note', icon: <Icon.Note /> },
      { name: 'overlays', icon: <Icon.Overlays /> },
      { name: 'panel-closed', icon: <Icon.PanelClosed /> },
      { name: 'panel-open', icon: <Icon.PanelOpen /> },
      { name: 'person', icon: <Icon.Person /> },
      { name: 'phone', icon: <Icon.Phone /> },
      { name: 'placeholder', icon: <Icon.Placeholder /> },
      { name: 'plots', icon: <Icon.Plots /> },
      { name: 'polygon-tool', icon: <Icon.PolygonTool /> },
      { name: 'radar', icon: <Icon.Radar /> },
      { name: 'radio', icon: <Icon.Radio /> },
      { name: 'rectangle-tool', icon: <Icon.RectangleTool /> },
      { name: 'region', icon: <Icon.Region /> },
      { name: 'sector', icon: <Icon.Sector /> },
      { name: 'selection-list', icon: <Icon.SelectionList /> },
      { name: 'sensor-health', icon: <Icon.SensorHealth /> },
      { name: 'settings', icon: <Icon.Settings /> },
      { name: 'spotlight', icon: <Icon.Spotlight /> },
      { name: 'threat-assess', icon: <Icon.ThreatAssess /> },
      { name: 'ticket', icon: <Icon.Ticket /> },
      { name: 'time', icon: <Icon.Time /> },
      { name: 'timer', icon: <Icon.Timer /> },
      { name: 'track-history', icon: <Icon.TrackHistory /> },
      {
        name: 'unscheduled-maintenance',
        icon: <Icon.UnscheduledMaintenance />,
      },
      { name: 'user-manual', icon: <Icon.UserManual /> },
      { name: 'watch-tower', icon: <Icon.WatchTower /> },
      { name: 'wind', icon: <Icon.Wind /> },
    ],
  },
  'map dynamic': {
    description: 'Icons that could represent entities on a map.',
    icons: [
      { name: 'commercial-ship', icon: <Icon.CommercialShip /> },
      { name: 'common-air-track', icon: <Icon.CommonAirTrack /> },
      { name: 'common-track', icon: <Icon.CommonTrack /> },
      { name: 'helicopter', icon: <Icon.Helicopter /> },
      { name: 'large-jet', icon: <Icon.LargeJet /> },
      { name: 'military-vessel', icon: <Icon.MilitaryVessel /> },
      { name: 'missile', icon: <Icon.Missile /> },
      { name: 'missiles', icon: <Icon.Missiles /> },
      { name: 'personal-boat', icon: <Icon.PersonalBoat /> },
      { name: 'prop', icon: <Icon.Prop /> },
      { name: 'small-jet', icon: <Icon.SmallJet /> },
      { name: 'uas', icon: <Icon.Uas /> },
    ],
  },
  'map static': {
    description: 'Icons that could represent entities on a map.',
    icons: [
      { name: 'airport', icon: <Icon.Airport /> },
      { name: 'alert-base', icon: <Icon.AlertBase /> },
      { name: 'alert', icon: <Icon.Alert /> },
      { name: 'artcc', icon: <Icon.Artcc /> },
      { name: 'bad-data', icon: <Icon.BadData /> },
      { name: 'battle-station', icon: <Icon.BattleStation /> },
      { name: 'birds', icon: <Icon.Birds /> },
      { name: 'building', icon: <Icon.Building /> },
      { name: 'car', icon: <Icon.Car /> },
      { name: 'chevron-down', icon: <Icon.ChevronDown /> },
      { name: 'chevron-up', icon: <Icon.ChevronUp /> },
      { name: 'connecting-airports', icon: <Icon.ConnectingAirports /> },
      { name: 'defended-point-caal-dal', icon: <Icon.DefendedPointCaalDal /> },
      { name: 'label', icon: <Icon.Label /> },
      { name: 'land', icon: <Icon.Land /> },
      { name: 'landmine', icon: <Icon.Landmine /> },
      { name: 'map-pin', icon: <Icon.MapPin /> },
      { name: 'marker', icon: <Icon.Marker /> },
      { name: 'military-airfield', icon: <Icon.MilitaryAirfield /> },
      { name: 'minus', icon: <Icon.Minus /> },
      { name: 'mission', icon: <Icon.Mission /> },
      { name: 'person', icon: <Icon.Person /> },
      { name: 'plus', icon: <Icon.Plus /> },
      { name: 'point-fill', icon: <Icon.PointFill /> },
      { name: 'point-outline', icon: <Icon.PointOutline /> },
      { name: 'presumed-target', icon: <Icon.PresumedTarget /> },
      { name: 'radar-anomaly', icon: <Icon.RadarAnomaly /> },
      { name: 'radar-site', icon: <Icon.RadarSite /> },
      { name: 'remote', icon: <Icon.Remote /> },
      { name: 'skull', icon: <Icon.Skull /> },
      { name: 'slash', icon: <Icon.Slash /> },
      { name: 'square-fill', icon: <Icon.SquareFill /> },
      { name: 'square-outline', icon: <Icon.SquareOutline /> },
      { name: 'stadium', icon: <Icon.Stadium /> },
      { name: 'star', icon: <Icon.Star /> },
      { name: 'target', icon: <Icon.Target /> },
      { name: 'terrain', icon: <Icon.Terrain /> },
      { name: 'track-eta-endpoint', icon: <Icon.TrackEtaEndpoint /> },
      { name: 'triangle-fill', icon: <Icon.TriangleFill /> },
      { name: 'triangle-outline', icon: <Icon.TriangleOutline /> },
      { name: 'uas-home-point', icon: <Icon.UasHomePoint /> },
      { name: 'waffle', icon: <Icon.Waffle /> },
      { name: 'weather', icon: <Icon.Weather /> },
    ],
  },
  controls: {
    description:
      'These icons portray acts or symbols related to control or configuration.',
    icons: [
      { name: 'arrow-down', icon: <Icon.ArrowDown /> },
      { name: 'arrow-left', icon: <Icon.ArrowLeft /> },
      { name: 'arrow-northeast', icon: <Icon.ArrowNortheast /> },
      { name: 'arrow-northwest', icon: <Icon.ArrowNorthwest /> },
      { name: 'arrow-right', icon: <Icon.ArrowRight /> },
      { name: 'arrow-southeast', icon: <Icon.ArrowSoutheast /> },
      { name: 'arrow-southeast', icon: <Icon.ArrowSouthwest /> },
      { name: 'arrow-up', icon: <Icon.ArrowUp /> },
      { name: 'arrow-keys', icon: <Icon.ArrowKeys /> },
      { name: 'arrow', icon: <Icon.Arrow /> },
      { name: 'chevron-down', icon: <Icon.ChevronDown /> },
      { name: 'chevron-fill-down', icon: <Icon.ChevronFillDown /> },
      { name: 'chevron-up', icon: <Icon.ChevronUp /> },
      { name: 'chevron-fill-up', icon: <Icon.ChevronFillUp /> },
      { name: 'chevron-left', icon: <Icon.ChevronLeft /> },
      { name: 'chevron-fill-left', icon: <Icon.ChevronFillLeft /> },
      { name: 'chevron-right', icon: <Icon.ChevronRight /> },
      { name: 'chevron-fill-right', icon: <Icon.ChevronFillRight /> },
      { name: 'cursor-crosshair', icon: <Icon.CursorCrosshair /> },
      { name: 'cursor-default', icon: <Icon.CursorDefault /> },
      { name: 'cursor-drag', icon: <Icon.CursorDrag /> },
      { name: 'track-eta', icon: <Icon.TrackEta /> },
      { name: 'mouse-left-click', icon: <Icon.MouseLeftClick /> },
      { name: 'mouse-middle-click', icon: <Icon.MouseMiddleClick /> },
      { name: 'mouse-right-click', icon: <Icon.MouseRightClick /> },
      { name: 'mouse-scroll', icon: <Icon.MouseScroll /> },
      { name: 'scroll-click', icon: <Icon.ScrollClick /> },
    ],
  },
  feedback: {
    description:
      'These icons portray communication or providing feedback to the user.',
    icons: [
      { name: 'bell', icon: <Icon.Bell /> },
      { name: 'information', icon: <Icon.Information /> },
      { name: 'connection', icon: <Icon.Connection /> },
      { name: 'success', icon: <Icon.Success /> },
      { name: 'connection-lost', icon: <Icon.ConnectionLost /> },
      { name: 'warning', icon: <Icon.Warning /> },
      { name: 'live', icon: <Icon.Live /> },
      { name: 'problem', icon: <Icon.Problem /> },
    ],
  },
};
