/*
 * Copyright 2025 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import {
  Add,
  AddFill,
  AddToList,
  Airspaces,
  Appearance,
  ArrangeTable,
  Arrow,
  ArrowDown,
  ArrowKeys,
  ArrowLeft,
  ArrowNortheast,
  ArrowNorthwest,
  ArrowRight,
  ArrowSoutheast,
  ArrowSouthwest,
  ArrowUp,
  Ascending,
  Assignment,
  AttachFile,
  Attributes,
  Bell,
  Bolt,
  BoltNotVisible,
  Brightness,
  BugReport,
  Calendar,
  Cancel,
  CancelFill,
  CenterOn,
  ChartStackedBar,
  Check,
  ChevronDown,
  ChevronFillDown,
  ChevronFillLeft,
  ChevronFillRight,
  ChevronFillUp,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleTool,
  CollapseAll,
  CollapseWindow,
  ColorPicker,
  CommonOperatingPic,
  Condense,
  Connection,
  ConnectionLost,
  Contrast,
  CopSettings,
  CopyToClipboard,
  Coverage,
  CreateCoa,
  CursorCrosshair,
  CursorDefault,
  CursorDrag,
  Dashboard,
  Data,
  Delete,
  Descending,
  DragHorz,
  DragVert,
  Duplicate,
  Edit,
  ElectromagneticSpectrum,
  Expand,
  ExpandAll,
  ExpandLeft,
  ExpandRight,
  ExpandWindow,
  ExploreData,
  Feed,
  Filter,
  Flag,
  FlightPlan,
  Focus,
  Gantt,
  GlobalShare,
  Grid,
  Group,
  Hamburger,
  Handover,
  Handshake,
  Help,
  Hide,
  Import,
  Information,
  InsertChart,
  InterceptPoint,
  JumpTo,
  Kebab,
  Lasso,
  LayerGroup,
  Layers,
  LineTool,
  Link,
  Live,
  LocationFill,
  LocationStroke,
  LockFill,
  LockOutline,
  Login,
  Logout,
  Loop,
  Message,
  Mode,
  MouseLeftClick,
  MouseMiddleClick,
  MouseRightClick,
  MouseScroll,
  Move,
  Mute,
  Newspaper,
  NonEditable,
  None,
  Note,
  OpenContainer,
  Overlays,
  PanelClosed,
  PanelOpen,
  PasteFromClipboard,
  Pause,
  Person,
  Phone,
  Pin,
  Placeholder,
  Play,
  Playback,
  Plots,
  PolygonLasso,
  PolygonTool,
  PopBackIn,
  PopOut,
  Problem,
  Radar,
  Radio,
  Record,
  RectangleSelect,
  RectangleTool,
  Region,
  Remove,
  RemoveFill,
  RemoveFromList,
  Reverse,
  Screenshot,
  ScrollClick,
  Search,
  Sector,
  SelectionList,
  SensorHealth,
  Settings,
  Share,
  Show,
  Spotlight,
  Stack,
  StackCards,
  Success,
  Tether,
  ThreatAssess,
  Ticket,
  Time,
  Timer,
  TrackChanges,
  TrackEta,
  TrackHistory,
  Undo,
  UnscheduledMaintenance,
  UserManual,
  Warning,
  WatchTower,
  Wind,
  ZoomIn,
  ZoomOut,
  ZoomTo,
} from '@accelint/icons';

export default {
  actions: {
    description:
      'These icons mainly represent an act a user can take in the user interface.',
    icons: [
      { name: 'add-fill', icon: <AddFill /> },
      { name: 'add-to-list', icon: <AddToList /> },
      { name: 'add', icon: <Add /> },
      { name: 'arrange-table', icon: <ArrangeTable /> },
      { name: 'attach-file', icon: <AttachFile /> },
      { name: 'cancel', icon: <Cancel /> },
      { name: 'cancel-fill', icon: <CancelFill /> },
      { name: 'center-on', icon: <CenterOn /> },
      { name: 'check', icon: <Check /> },
      { name: 'collapse-window', icon: <CollapseWindow /> },
      { name: 'collapse-all', icon: <CollapseAll /> },
      { name: 'condense', icon: <Condense /> },
      { name: 'copy-to-clipboard', icon: <CopyToClipboard /> },
      { name: 'create-coa', icon: <CreateCoa /> },
      { name: 'delete', icon: <Delete /> },
      { name: 'drag-horz', icon: <DragHorz /> },
      { name: 'drag-vert', icon: <DragVert /> },
      { name: 'duplicate', icon: <Duplicate /> },
      { name: 'edit', icon: <Edit /> },
      { name: 'expand-all', icon: <ExpandAll /> },
      { name: 'expand-left', icon: <ExpandLeft /> },
      { name: 'expand-right', icon: <ExpandRight /> },
      { name: 'expand-window', icon: <ExpandWindow /> },
      { name: 'expand', icon: <Expand /> },
      { name: 'explore-data', icon: <ExploreData /> },
      { name: 'filter', icon: <Filter /> },
      { name: 'flag', icon: <Flag /> },
      { name: 'focus', icon: <Focus /> },
      { name: 'global-share', icon: <GlobalShare /> },
      { name: 'group', icon: <Group /> },
      { name: 'hide', icon: <Hide /> },
      { name: 'import', icon: <Import /> },
      { name: 'insert-chart', icon: <InsertChart /> },
      { name: 'jump-to', icon: <JumpTo /> },
      { name: 'lasso', icon: <Lasso /> },
      { name: 'link', icon: <Link /> },
      { name: 'lock-fill', icon: <LockFill /> },
      { name: 'lock-outline', icon: <LockOutline /> },
      { name: 'login', icon: <Login /> },
      { name: 'logout', icon: <Logout /> },
      { name: 'loop', icon: <Loop /> },
      { name: 'move', icon: <Move /> },
      { name: 'mute', icon: <Mute /> },
      { name: 'open-container', icon: <OpenContainer /> },
      { name: 'paste-from-clipboard', icon: <PasteFromClipboard /> },
      { name: 'pause', icon: <Pause /> },
      { name: 'pin', icon: <Pin /> },
      { name: 'play', icon: <Play /> },
      { name: 'playback', icon: <Playback /> },
      { name: 'polygon-lasso', icon: <PolygonLasso /> },
      { name: 'pop-back-in', icon: <PopBackIn /> },
      { name: 'pop-out', icon: <PopOut /> },
      { name: 'record', icon: <Record /> },
      { name: 'rectangle-select', icon: <RectangleSelect /> },
      { name: 'remove-fill', icon: <RemoveFill /> },
      { name: 'remove-from-list', icon: <RemoveFromList /> },
      { name: 'remove', icon: <Remove /> },
      { name: 'reverse', icon: <Reverse /> },
      { name: 'screenshot', icon: <Screenshot /> },
      { name: 'search', icon: <Search /> },
      { name: 'share', icon: <Share /> },
      { name: 'show', icon: <Show /> },
      { name: 'stack-cards', icon: <StackCards /> },
      { name: 'stack', icon: <Stack /> },
      { name: 'tether', icon: <Tether /> },
      { name: 'track-changes', icon: <TrackChanges /> },
      { name: 'undo', icon: <Undo /> },
      { name: 'zoom-in', icon: <ZoomIn /> },
      { name: 'zoom-out', icon: <ZoomOut /> },
      { name: 'zoom-to', icon: <ZoomTo /> },
    ],
  },
  symbols: {
    description: 'These icons mainly represent an object or concept.',
    icons: [
      { name: 'airspaces', icon: <Airspaces /> },
      { name: 'appearance', icon: <Appearance /> },
      { name: 'arrow', icon: <Arrow /> },
      { name: 'ascending', icon: <Ascending /> },
      { name: 'assignment', icon: <Assignment /> },
      { name: 'attributes', icon: <Attributes /> },
      { name: 'bolt-not-visible', icon: <BoltNotVisible /> },
      { name: 'bolt', icon: <Bolt /> },
      { name: 'brightness', icon: <Brightness /> },
      { name: 'bug-report', icon: <BugReport /> },
      { name: 'calendar', icon: <Calendar /> },
      { name: 'chart-stacked-bar', icon: <ChartStackedBar /> },
      { name: 'circle-tool', icon: <CircleTool /> },
      { name: 'color-picker', icon: <ColorPicker /> },
      { name: 'common-operating-pic', icon: <CommonOperatingPic /> },
      { name: 'contrast', icon: <Contrast /> },
      { name: 'cop-settings', icon: <CopSettings /> },
      { name: 'coverage', icon: <Coverage /> },
      { name: 'dashboard', icon: <Dashboard /> },
      { name: 'data', icon: <Data /> },
      { name: 'descending', icon: <Descending /> },
      { name: 'electromagnetic-spectrum', icon: <ElectromagneticSpectrum /> },
      { name: 'feed', icon: <Feed /> },
      { name: 'flight-plan', icon: <FlightPlan /> },
      { name: 'gantt', icon: <Gantt /> },
      { name: 'grid', icon: <Grid /> },
      { name: 'hamburger', icon: <Hamburger /> },
      { name: 'handover', icon: <Handover /> },
      { name: 'handshake', icon: <Handshake /> },
      { name: 'help', icon: <Help /> },
      { name: 'intercept-point', icon: <InterceptPoint /> },
      { name: 'kebab', icon: <Kebab /> },
      { name: 'layer-group', icon: <LayerGroup /> },
      { name: 'layers', icon: <Layers /> },
      { name: 'line-tool', icon: <LineTool /> },
      { name: 'location-fill', icon: <LocationFill /> },
      { name: 'location-stroke', icon: <LocationStroke /> },
      { name: 'message', icon: <Message /> },
      { name: 'mode', icon: <Mode /> },
      { name: 'newspaper', icon: <Newspaper /> },
      { name: 'non-editable', icon: <NonEditable /> },
      { name: 'none', icon: <None /> },
      { name: 'note', icon: <Note /> },
      { name: 'overlays', icon: <Overlays /> },
      { name: 'panel-closed', icon: <PanelClosed /> },
      { name: 'panel-open', icon: <PanelOpen /> },
      { name: 'person', icon: <Person /> },
      { name: 'phone', icon: <Phone /> },
      { name: 'placeholder', icon: <Placeholder /> },
      { name: 'plots', icon: <Plots /> },
      { name: 'polygon-tool', icon: <PolygonTool /> },
      { name: 'radar', icon: <Radar /> },
      { name: 'radio', icon: <Radio /> },
      { name: 'rectangle-tool', icon: <RectangleTool /> },
      { name: 'region', icon: <Region /> },
      { name: 'sector', icon: <Sector /> },
      { name: 'selection-list', icon: <SelectionList /> },
      { name: 'sensor-health', icon: <SensorHealth /> },
      { name: 'settings', icon: <Settings /> },
      { name: 'spotlight', icon: <Spotlight /> },
      { name: 'threat-assess', icon: <ThreatAssess /> },
      { name: 'ticket', icon: <Ticket /> },
      { name: 'time', icon: <Time /> },
      { name: 'timer', icon: <Timer /> },
      { name: 'track-history', icon: <TrackHistory /> },
      { name: 'unscheduled-maintenance', icon: <UnscheduledMaintenance /> },
      { name: 'user-manual', icon: <UserManual /> },
      { name: 'watch-tower', icon: <WatchTower /> },
      { name: 'wind', icon: <Wind /> },
    ],
  },
  controls: {
    description:
      'These icons portray acts or symbols related to control or configuration.',
    icons: [
      { name: 'arrow-down', icon: <ArrowDown /> },
      { name: 'arrow-left', icon: <ArrowLeft /> },
      { name: 'arrow-northeast', icon: <ArrowNortheast /> },
      { name: 'arrow-northwest', icon: <ArrowNorthwest /> },
      { name: 'arrow-right', icon: <ArrowRight /> },
      { name: 'arrow-southeast', icon: <ArrowSoutheast /> },
      { name: 'arrow-southeast', icon: <ArrowSouthwest /> },
      { name: 'arrow-up', icon: <ArrowUp /> },
      { name: 'arrow-keys', icon: <ArrowKeys /> },
      { name: 'arrow', icon: <Arrow /> },
      { name: 'chevron-down', icon: <ChevronDown /> },
      { name: 'chevron-fill-down', icon: <ChevronFillDown /> },
      { name: 'chevron-up', icon: <ChevronUp /> },
      { name: 'chevron-fill-up', icon: <ChevronFillUp /> },
      { name: 'chevron-left', icon: <ChevronLeft /> },
      { name: 'chevron-fill-left', icon: <ChevronFillLeft /> },
      { name: 'chevron-right', icon: <ChevronRight /> },
      { name: 'chevron-fill-right', icon: <ChevronFillRight /> },
      { name: 'cursor-crosshair', icon: <CursorCrosshair /> },
      { name: 'cursor-default', icon: <CursorDefault /> },
      { name: 'cursor-drag', icon: <CursorDrag /> },
      { name: 'track-eta', icon: <TrackEta /> },
      { name: 'mouse-left-click', icon: <MouseLeftClick /> },
      { name: 'mouse-middle-click', icon: <MouseMiddleClick /> },
      { name: 'mouse-right-click', icon: <MouseRightClick /> },
      { name: 'mouse-scroll', icon: <MouseScroll /> },
      { name: 'scroll-click', icon: <ScrollClick /> },
    ],
  },
  feedback: {
    description:
      'These icons portray communication or providing feedback to the user.',
    icons: [
      { name: 'bell', icon: <Bell /> },
      { name: 'information', icon: <Information /> },
      { name: 'connection', icon: <Connection /> },
      { name: 'success', icon: <Success /> },
      { name: 'connection-lost', icon: <ConnectionLost /> },
      { name: 'warning', icon: <Warning /> },
      { name: 'live', icon: <Live /> },
      { name: 'problem', icon: <Problem /> },
    ],
  },
};
